package com.vaibhav.util

object Constants {

    const val API_VERSION = "v1"
    const val TYPE_JOIN_ROOM = "TYPE_JOIN_ROOM"
    const val TYPE_PHASE_CHANGE = "TYPE_PHASE_CHANGE"
    const val TYPE_PLAYER_EVENT = "TYPE_PLAYER_EVENT"
    const val TYPE_DISCONNECT_REQUEST = "TYPE_DISCONNECT_REQUEST"
    const val TYPE_GAME_MOVE = "TYPE_GAME_MOVE"
    const val TYPE_START_GAME = "TYPE_START_GAME"
    const val TYPE_ANNOUNCEMENT = "TYPE_ANNOUNCEMENT"
    const val TYPE_GAME_RESULT = "TYPE_GAME_RESULT"
    const val TYPE_GAME_BOARD_STATE_CHANGED = "TYPE_GAME_BOARD_STATE_CHANGED"
}